data_path: ./   # 数据存放路径

# 匹配
# registration_method: NDT   # 选择点云匹配方法，目前支持：NDT 
# registration_method: ICP   # 选择点云匹配方法，目前支持：NDT 
registration_method: MY_ICP  


# 局部地图
key_frame_distance: 2.0 # 关键帧距离
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter

# rviz显示
display_filter: voxel_filter # rviz 实时显示点云时滤波方法，目前支持：voxel_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

# 各配置选项对应参数
## 匹配相关参数
NDT:
    res : 1.0               # 分辨率
    step_size : 0.1         # 步长
    trans_eps : 0.01        # 收敛阈值
    max_iter : 30           # 最大迭代次数

## ICP 
ICP:
    max_distance : 1        # 最大欧式距离差值
    fit_eps : 0.01          # 设置前后两次迭代的点对的欧式距离均值的最大容差，迭代终止条件之三，默认值为：-std::numeric_limits::max ()
    trans_eps : 0.01       # 收敛阈值
    max_iter : 30           # 最大迭代次数

## MY_ICP
MY_ICP:
    max_distance : 1        # 最大欧式距离差值
    max_iter : 30           # 最大迭代次数




## 滤波相关参数
voxel_filter:
    local_map:
        leaf_size: [0.6, 0.6, 0.6]
    frame:
        leaf_size: [1.3, 1.3, 1.3]
    display:
        leaf_size: [0.5, 0.5, 0.5]